steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_AR_HOSTNAME/$PROJECT_ID/portifolio/$_SERVICE_NAME:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_AR_HOSTNAME/$PROJECT_ID/portifolio/$_SERVICE_NAME:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'portifolio-web',
        '--image',
        '$_AR_HOSTNAME/$PROJECT_ID/portifolio/$_SERVICE_NAME:latest',
        '--region',
        '$_DEPLOY_REGION'
      ]
images:
  - '$_AR_HOSTNAME/$PROJECT_ID/portifolio/$_SERVICE_NAME:latest'

options:
  logging: CLOUD_LOGGING_ONLY
